#!/bin/bash

cc="g++ -std=c++11"
lib=''
fichierO=''
creationO=''
cppFiles=''
libmat="lib/"
obj="obj/"
bin="bin/"
src="src/"
librairie="librairie.a"
executable="Executable"
sfml = ""

cd `pwd`



>makefile

echo -e "all : lib\n">>makefile

if test ! -d "src"
then
	mkdir "src"
fi

if test ! -d "include"
then
	mkdir "include"
fi

if test ! -d "obj"
then
	mkdir "obj"
fi

if test ! -d "lib"
then
	mkdir "lib"
fi

if test ! -d "bin"
then
	mkdir "bin"
fi

for f in *.h
do
	if test -f $f
	then
			mv $f "include/$f"
	fi
done

for f in *.cpp
do
	if test -f $f
	then
			mv $f "src/$f"
	fi
done

cd src

for i in *
do
	v=`echo $i | tr [a-z] [A-Z]`
	m=`echo $i | tr [A-Z] [a-z]`
	if [ $v != "MAIN.CPP" ]
	then
		fichierO="$fichierO$obj`basename $i .cpp`.o " #liste des fichiers .o sauf le main.o
		creationO="$creationO$obj`basename $i .cpp`.o : $src$i\n\tg++ -std=c++11 -pthread -o $obj`basename $i .cpp`.o -c $src$i\n"
		cppFiles="$cppFiles$src$i "
	fi
	if  [ $v == "MAIN.CPP" ]
	then
		if [ $i != "main.cpp" ]
		then
			mv $i $m
		fi
		i=$m
		r=$m
	fi
	lib="$lib $obj`basename $i .cpp`.o" #liste de tout les fichiers .o
done

cd ..

echo -e "lib: $lib\n\tar -q $libmat$librairie $fichierO\n\tg++ -std=c++11 -pthread -o $bin$executable $src$r $cppFiles -L /usr/include/SFML -lsfml-graphics -lsfml-window -lsfml-system $libmat$librairie\n">>makefile

#creation du Main
echo -e "$obj`basename $r .cpp`.o :  $src$r\n\tg++ -std=c++11 -pthread -o $obj`basename $r .cpp`.o -c $src$r\n">>makefile

#creation des autre fichiers .o
echo -e "$creationO">>makefile

echo -e "clean:\n	rm -rf obj/*.o\nmrproper: clean\n	rm -rf bin/"$executable>>makefile



make
reset

cd bin

./$executable
